base_url = "https://www.gdmunion.co.uk"
title = "GDM Union"
description = "Google DeepMind employees unionising with UTAW to build AI responsibly to benefit humanity."
default_language = "en"
minify_html = false
generate_feeds = false
